sum of sequence

importing libraries

In [ ]:
import torch #tensor operations ad gpu accerlation
import torch.nn as nn #define neural network layers
import torch.optim  as optim #provide optimisers
import numpy as np

dataset creation,trainig of dataset

In [ ]:
sequence_length=15 #time steps per sequence
num_samples=200 #dataset with 200 sequences each of length 15

x_data = np.random.rand(num_samples, sequence_length,1) #1=feature size
y_data = np.sum(x_data, axis=1)#reduces the shape to (100,1)

x_train = torch.tensor(x_data,dtype=torch.float32)#converts data into pytorch tensor
y_train = torch.tensor(y_data,dtype=torch.float32)

rnn layer

In [ ]:


class SimpleRNN(nn.Module):  # Corrected class name and inheritance
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNN, self).__init__()  ##super- #Model parameters are registered properly.
#Forward and backward propagation work correctly.
#Saving & loading the model functions properly.

        # Store the hidden size
        self.hidden_size = hidden_size

        # Define the RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)

        # Fully connected layer (to map hidden state to output)
        self.fc = nn.Linear(hidden_size, output_size)


forward pass

In [ ]:
def forward(self, x):
    out, _ = self.rnn(x)  # Pass input through RNN,_  represents final hidden state
    out = self.fc(out[:, -1, :])  # Use the last time step output
    return out  # converts hidden representation into final output
# Model parameters
input_size = 1
hidden_size = 16
output_size = 1

model = SimpleRNN(input_size, hidden_size, output_size)

loss,optimiser

In [ ]:
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [ ]:
import numpy as np

# Initialize parameters
np.random.seed(42)
input_size = 1  # Single number input
hidden_size = 10  # Number of hidden neurons
output_size = 1  # Single output (sum)
learning_rate = 0.01
timesteps = 5  # Sequence length

# Random weight initialization
Wxh = np.random.randn(hidden_size, input_size) * 0.01  # Input to hidden
Whh = np.random.randn(hidden_size, hidden_size) * 0.01  # Hidden to hidden
Why = np.random.randn(output_size, hidden_size) * 0.01  # Hidden to output
bh = np.zeros((hidden_size, 1))  # Hidden bias
by = np.zeros((output_size, 1))  # Output bias

# Activation function
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

# Training data: sequences and their sums
X_train = np.random.randint(1, 10, (100, timesteps, 1))  # 100 sequences of length 5
Y_train = np.sum(X_train, axis=1, keepdims=True)  # Sum of each sequence

# Training loop
for epoch in range(1000):  # Train for 1000 epochs
    total_loss = 0

    # Initialize gradients
    dWxh, dWhh, dWhy = np.zeros_like(Wxh), np.zeros_like(Whh), np.zeros_like(Why)
    dbh, dby = np.zeros_like(bh), np.zeros_like(by)

    for x, y_true in zip(X_train, Y_train):
        # Forward Pass
        h = np.zeros((hidden_size, 1))  # Initial hidden state
        h_cache, x_cache = [], []

        for t in range(timesteps):
            x_t = x[t].reshape(input_size, 1)
            h = tanh(np.dot(Wxh, x_t) + np.dot(Whh, h) + bh)
            h_cache.append(h)
            x_cache.append(x_t)

        y_pred = np.dot(Why, h) + by
        loss = 0.5 * (y_pred - y_true) ** 2  # MSE loss
        total_loss += loss

        # Backward Pass (BPTT)
        dy = y_pred - y_true
        dWhy += np.dot(dy, h.T)
        dby += dy
        dh_next = np.dot(Why.T, dy)

     for t in reversed(range(timesteps)):
    dh = dh_next + np.dot(Whh.T, dh_next)
    dtanh = tanh_derivative(h_cache[t]) * dh
    dWxh += np.dot(dtanh, x_cache[t].T)
    dWhh += np.dot(dtanh, h_cache[t-1].T) if t > 0 else np.zeros_like(dWhh)
    dbh += dtanh
    dh_next = np.dot(Whh.T, dtanh)


        # Gradient Clipping
        for dparam in [dWxh, dWhh, dWhy, dbh, dby]:
            np.clip(dparam, -5, 5, out=dparam)

        # Update Weights
        Wxh -= learning_rate * dWxh
        Whh -= learning_rate * dWhh
        Why -= learning_rate * dWhy
        bh -= learning_rate * dbh
        by -= learning_rate * dby

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {total_loss.mean()}")

# Testing the trained model
test_seq = np.array([[1], [2], [3], [4], [5]])  # Sum should be 15
h = np.zeros((hidden_size, 1))
for t in range(timesteps):
    x_t = test_seq[t].reshape(input_size, 1)
    h = tanh(np.dot(Wxh, x_t) + np.dot(Whh, h) + bh)

y_pred = np.dot(Why, h) + by
print("Predicted sum:", y_pred.flatten()[0])


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 58)

train  the model

predicyions

In [ ]:
with torch.no_grad():#disables gradient calculations to save memory and space,used during evaluation or testing
    test_sample = torch.tensor(np.random.rand(1, sequence_length, 1), dtype=torch.float32)
    prediction = model(test_sample)
    print(f'Predicted sum: {prediction.item()}, Actual sum: {np.sum(test_sample.numpy()):.4f}')


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Define the RNN Model
class SimpleRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNN, self).__init__()
        self.hidden_size = hidden_size
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.rnn(x)  # Process input through RNN
        out = self.fc(out[:, -1, :])  # Use the last time step output
        return out

# Model Parameters
input_size = 1
hidden_size = 16
output_size = 1
num_epochs = 100
learning_rate = 0.01

# Generate Sequential Dataset
sequence_length = 10
num_samples = 100

x_data = np.random.rand(num_samples, sequence_length, 1)
y_data = np.sum(x_data, axis=1)

x_train = torch.tensor(x_data, dtype=torch.float32)
y_train = torch.tensor(y_data, dtype=torch.float32).unsqueeze(1)  # Reshape to (batch_size, 1)

# Define Model, Loss, and Optimizer
model = SimpleRNN(input_size, hidden_size, output_size)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training Loop
for epoch in range(num_epochs):
    optimizer.zero_grad() # Clear previously accumulated gradients to prevent accumulation
    outputs = model(x_train)  # Forward pass
    loss = criterion(outputs, y_train)  # Compute loss
    loss.backward()  # Backpropagation
    optimizer.step()  # Update weights

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([100, 1, 1])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch [10/100], Loss: 7.6887
Epoch [20/100], Loss: 1.2599
Epoch [30/100], Loss: 0.7487
Epoch [40/100], Loss: 0.8924
Epoch [50/100], Loss: 0.6685
Epoch [60/100], Loss: 0.6554
Epoch [70/100], Loss: 0.6545
Epoch [80/100], Loss: 0.6436
Epoch [90/100], Loss: 0.6451
Epoch [100/100], Loss: 0.6437


forward propagation

In [ ]:
import numpy as np

# Activation function (tanh for hidden state)
def tanh(x):
    return np.tanh(x)

# Softmax for output (if classification task)
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # For numerical stability
    return exp_x / np.sum(exp_x, axis=0, keepdims=True)

# Initialize parameters
input_size = 3   # Number of input features
hidden_size = 4  # Number of hidden units
output_size = 2  # Number of output classes

np.random.seed(42)  # For reproducibility
W_x = np.random.randn(hidden_size, input_size)   # Input to hidden weights
W_h = np.random.randn(hidden_size, hidden_size)  # Hidden to hidden weights
W_y = np.random.randn(output_size, hidden_size)  # Hidden to output weights
b_h = np.zeros((hidden_size, 1))  # Hidden bias
b_y = np.zeros((output_size, 1))  # Output bias

# Sample input sequence (3 time steps, each with `input_size` features)
X = [np.random.randn(input_size, 1) for _ in range(3)]

# Forward propagation
h_t = np.zeros((hidden_size, 1))  # Initial hidden state

for t in range(len(X)):
    h_t = tanh(W_x @ X[t] + W_h @ h_t + b_h)  # Hidden state update
    y_t = softmax(W_y @ h_t + b_y)  # Output computation
    print(f"Time step {t+1} - Hidden state:\n{h_t}\nOutput:\n{y_t}\n")


Time step 1 - Hidden state:
[[-0.45067975]
 [ 0.79612735]
 [-0.50091697]
 [ 0.92747852]]
Output:
[[0.9883202]
 [0.0116798]]

Time step 2 - Hidden state:
[[-0.82841336]
 [-0.06152805]
 [-0.88500024]
 [ 0.73679606]]
Output:
[[0.98136662]
 [0.01863338]]

Time step 3 - Hidden state:
[[ 0.0560443 ]
 [ 0.67684836]
 [-0.96604458]
 [ 0.98674592]]
Output:
[[0.99256322]
 [0.00743678]]

