In [ ]:
!pip install transformers

In [ ]:
from transformers import pipeline

# Load a pre-trained BERT model for sentiment analysis
classifier = pipeline("text-classification", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Example text input
texts = [
    "I love this product! It's amazing.",
    "The service was terrible and disappointing."
]

# Perform classification
results = classifier(texts)

# Print results
for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Prediction: {result['label']}, Confidence: {result['score']:.4f}\n")


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu


Text: I love this product! It's amazing.
Prediction: 5 stars, Confidence: 0.9424

Text: The service was terrible and disappointing.
Prediction: 1 star, Confidence: 0.6538



In [ ]:
from transformers import pipeline

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
classifier = pipeline('sentiment-analysis', model=model_name)

result = classifier("I love using Hugging Face transformers!")
print(result)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9971315860748291}]


mini tramsformer

In [ ]:
!pip install torch torchvision torchaudio


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 92.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 73.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 46.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 80.8 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
import torch

# Fake word embeddings (each word has a vector of 4 numbers)
sentence = torch.tensor([
    [0.1, 0.2, 0.3, 0.4],  # "I"
    [0.2, 0.1, 0.4, 0.3],  # "love"
    [0.3, 0.4, 0.1, 0.2]   # "pizza"
])

# Add batch dimension (1 sentence, 3 words, 4 features per word)
sentence = sentence.unsqueeze(0)

print(sentence.shape)  # Output: torch.Size([1, 3, 4])


torch.Size([1, 3, 4])


In [ ]:
import torch.nn as nn

# Define weight matrices for Query, Key, and Value
embed_size = 4  # Embedding size of words
W_q = nn.Linear(embed_size, embed_size, bias=False)  # Query weight matrix
W_k = nn.Linear(embed_size, embed_size, bias=False)  # Key weight matrix
W_v = nn.Linear(embed_size, embed_size, bias=False)  # Value weight matrix

# Apply transformations
Q = W_q(sentence)  # Queries
K = W_k(sentence)  # Keys
V = W_v(sentence)  # Values

print(Q.shape, K.shape, V.shape)  # Output: torch.Size([1, 3, 4])


torch.Size([1, 3, 4]) torch.Size([1, 3, 4]) torch.Size([1, 3, 4])


In [ ]:
# Compute attention scores (Q @ K^T)
scores = torch.matmul(Q, K.transpose(-2, -1))

print(scores.shape)  # Output: torch.Size([1, 3, 3])
print(scores)  # Shows the attention scores


torch.Size([1, 3, 3])
tensor([[[0.0351, 0.0270, 0.0124],
         [0.0420, 0.0355, 0.0128],
         [0.0643, 0.0513, 0.0306]]], grad_fn=<UnsafeViewBackward0>)


In [ ]:
import torch.nn.functional as F

# Apply softmax to get attention weights
attention_weights = F.softmax(scores, dim=-1)

print(attention_weights.shape)  # Output: torch.Size([1, 3, 3])
print(attention_weights)  # Shows normalized attention values


torch.Size([1, 3, 3])
tensor([[[0.3368, 0.3340, 0.3292],
         [0.3373, 0.3351, 0.3276],
         [0.3385, 0.3342, 0.3273]]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# Multiply attention weights with Values (V)
output = torch.matmul(attention_weights, V)

print(output.shape)  # Output: torch.Size([1, 3, 4])
print(output)  # Shows the transformed sentence


torch.Size([1, 3, 4])
tensor([[[-0.0114,  0.1571, -0.2074,  0.0670],
         [-0.0116,  0.1572, -0.2071,  0.0672],
         [-0.0115,  0.1574, -0.2071,  0.0673]]], grad_fn=<UnsafeViewBackward0>)


In [ ]:
import torch.nn as nn  # Neural network module

class SimpleTransformerBlock(nn.Module):
    def __init__(self, embed_size, heads):
        super(SimpleTransformerBlock, self).__init__()
        self.attention = nn.MultiheadAttention(embed_dim=embed_size, num_heads=heads)
        self.norm = nn.LayerNorm(embed_size)

    def forward(self, x):
        attn_output, _ = self.attention(x, x, x)  # Self-Attention
        x = self.norm(attn_output + x)  # Skip Connection + Normalization
        return x


In [ ]:
# Define model
embed_size = 4  # Same as word embedding size
heads = 2       # Number of attention heads

model = SimpleTransformerBlock(embed_size, heads)

# Run model on sentence
output = model(sentence)

print(output.shape)  # Output: torch.Size([1, 3, 4])
print(output)  # View transformed sentence


torch.Size([1, 3, 4])
tensor([[[-1.4493,  1.2462, -0.3006,  0.5037],
         [-1.5768,  0.1197,  1.1917,  0.2653],
         [ 0.0982,  1.5835, -1.0255, -0.6562]]],
       grad_fn=<NativeLayerNormBackward0>)
